update stable packs to reflect recent dev work

diff --git a/packs/stable/lang-pack/lib/haskell-mode/Makefile b/packs/stable/lang-pack/lib/haskell-mode/Makefile
--- a/packs/stable/lang-pack/lib/haskell-mode/Makefile
+++ b/packs/stable/lang-pack/lib/haskell-mode/Makefile
@@ -10,7 +10,7 @@
 # We should have a script that changes it everywhere it is needed and
 # syncs it with current git tag.
 #
-VERSION = 13.15-git
+VERSION = 13.20
 
 INSTALL_INFO = install-info
 
@@ -23,68 +23,29 @@ INSTALL_INFO = install-info
 #
 # This is particularly useful when EMACS is set in ~/.bash_profile
 #
-EMACS := $(shell echo "$${EMACS:-emacs}")
+EMACS := $(shell which "$${EMACS}" || which "emacs")
+EMACS_VERSION := $(shell "$(EMACS)" -Q --batch --eval '(princ emacs-version)')
 
 EFLAGS = --eval "(add-to-list 'load-path (expand-file-name \"tests/compat\") 'append)" \
 	 --eval "(when (< emacs-major-version 24) \
 		    (setq byte-compile-warnings '(not cl-functions)))" \
-	 --eval '(setq byte-compile-error-on-warn t)'
+	 --eval '(setq byte-compile-error-on-warn t)' \
+	 --eval '(when (not (version< emacs-version "24.4")) (setq load-prefer-newer t))' \
+	 --eval '(defun byte-compile-dest-file (filename) \
+                    (concat (file-name-directory filename) "build-" emacs-version "/" \
+                            (file-name-nondirectory filename) "c"))'
 
 BATCH = $(EMACS) $(EFLAGS) --batch -Q -L .
 
-ELFILES = \
-	ghc-core.el \
-	ghci-script-mode.el \
-	highlight-uses-mode.el \
-	haskell-align-imports.el \
-	haskell-bot.el \
-	haskell-cabal.el \
-	haskell-checkers.el \
-	haskell-collapse.el \
-	haskell-modules.el \
-	haskell-sandbox.el \
-	haskell-commands.el \
-	haskell-compat.el \
-	haskell-compile.el \
-	haskell-complete-module.el \
-	haskell-completions.el \
-	haskell-customize.el \
-	haskell-debug.el \
-	haskell-decl-scan.el \
-	haskell-doc.el \
-	haskell.el \
-	haskell-font-lock.el \
-	haskell-indentation.el \
-	haskell-indent.el \
-	haskell-interactive-mode.el \
-	haskell-load.el \
-	haskell-menu.el \
-	haskell-mode.el \
-	haskell-move-nested.el \
-	haskell-navigate-imports.el \
-	haskell-package.el \
-	haskell-presentation-mode.el \
-	haskell-process.el \
-	haskell-repl.el \
-	haskell-session.el \
-	haskell-simple-indent.el \
-	haskell-sort-imports.el \
-	haskell-string.el \
-	haskell-unicode-input-method.el \
-	haskell-utils.el \
-	inf-haskell.el
+ELFILES := $(filter-out haskell-mode-autoloads.el haskell-mode-pkg.el,$(wildcard *.el))
 
-ELCFILES = $(ELFILES:.el=.elc)
+ELCHECKS := $(wildcard tests/*-tests.el)
+
 AUTOLOADS = haskell-mode-autoloads.el
 
 PKG_DIST_FILES = $(ELFILES) logo.svg NEWS haskell-mode.info dir
-ELCHECKS=$(addprefix check-, $(ELFILES:.el=))
 
-%.elc: %.el
-	@$(BATCH) \
-		 -f batch-byte-compile $*.el
-
-.PHONY: all compile info clean check $(ELCHECKS) elpa package check-emacs-version
+.PHONY: all compile info clean check check-emacs-version
 
 all: check-emacs-version compile $(AUTOLOADS) info
 
@@ -99,20 +60,36 @@ check-emacs-version :
                             (message \"   3.  make EMACS=/path/to/emacs\")			\
                             (kill-emacs 2))"
 
-compile: $(ELCFILES)
+compile: build-$(EMACS_VERSION)
 
-$(ELCHECKS): check-%: %.el %.elc
-	@$(BATCH) --eval '(when (check-declare-file "$*.el") (error "check-declare failed"))'
-	@if [ -f "$(<:%.el=tests/%-tests.el)" ]; then \
-		$(BATCH) -l "$(<:%.el=tests/%-tests.el)" -f ert-run-tests-batch-and-exit; \
+build-$(EMACS_VERSION) : $(ELFILES)
+	if [ ! -d $@ ]; then mkdir $@; fi
+	$(BATCH) -f batch-byte-compile-if-not-done $^
+
+check-%: tests/%-tests.el
+	$(BATCH) -l "$<" -f ert-run-tests-batch-and-exit;
+
+check: $(ELCHECKS) build-$(EMACS_VERSION)
+	$(BATCH) --eval "(when (= emacs-major-version 24)					\
+                           (require 'undercover)						\
+                           (undercover \"*.el\"							\
+                              (:exclude \"haskell-mode-pkg.el\" \"haskell-compat.el\")))"	\
+                 -L tests									\
+                 $(patsubst %,-l %,$(ELCHECKS))							\
+                 -f ert-run-tests-batch-and-exit
+	@TAB=$$(echo "\t"); \
+	if grep -Hn "[ $${TAB}]\+\$$" *.el tests/*.el; then \
+	    echo "Error: Files contain whitespace at the end of lines" >&2; \
+	    exit 3; \
+	fi; \
+	if grep -Hn "[$${TAB}]" *.el tests/*.el; then \
+	    echo "Error: Tab character is not allowed" >&2; \
+	    exit 3; \
 	fi
-	@echo "--"
-
-check: $(ELCHECKS)
 	@echo "checks passed!"
 
 clean:
-	$(RM) $(ELCFILES) $(AUTOLOADS) $(AUTOLOADS:.el=.elc) haskell-mode.info dir
+	$(RM) -r build-$(EMACS_VERSION) $(AUTOLOADS) $(AUTOLOADS:.el=.elc) haskell-mode.info dir
 
 info: haskell-mode.info dir
 
@@ -124,15 +101,19 @@ haskell-mode.info: doc/haskell-mode.texi
 
 doc/haskell-mode.html: doc/haskell-mode.texi doc/haskell-mode.css
 	LANG=en_US.UTF-8 $(MAKEINFO) $(MAKEINFO_FLAGS) --html --css-include=doc/haskell-mode.css --no-split -o $@ $<
+	$(BATCH) -l doc/haskell-manual-fixups.el -f haskell-manual-fixups-batch-and-exit $@
 
 doc/html/index.html : doc/haskell-mode.texi
 	if [ -e doc/html ]; then rm -r doc/html; fi
+	mkdir doc/html
+	cp -r doc/anim doc/html/anim
 	LANG=en_US.UTF-8 $(MAKEINFO) $(MAKEINFO_FLAGS) --html				\
 	    --css-ref=haskell-mode.css							\
 	    -c AFTER_BODY_OPEN='<div class="background"> </div>'			\
 	    -c EXTRA_HEAD='<link rel="shortcut icon" href="haskell-mode-32x32.png">'	\
 	    -c SHOW_TITLE=0								\
 	    -o doc/html $<
+	$(BATCH) -l doc/haskell-manual-fixups.el -f haskell-manual-fixups-batch-and-exit doc/html/*.html
 
 doc/html/haskell-mode.css : doc/haskell-mode.css doc/html/index.html
 	cp $< $@
@@ -143,13 +124,18 @@ doc/html/haskell-mode.svg : images/haskell-mode.svg doc/html/index.html
 doc/html/haskell-mode-32x32.png : images/haskell-mode-32x32.png doc/html/index.html
 	cp $< $@
 
-doc/html : doc/html/index.html doc/html/haskell-mode.css doc/html/haskell-mode.svg doc/html/haskell-mode-32x32.png
+doc/html : doc/html/index.html			\
+           doc/html/haskell-mode.css		\
+           doc/html/haskell-mode.svg		\
+           doc/html/haskell-mode-32x32.png
 
 deploy-manual : doc/html
 	cd doc && ./deploy-manual.sh
 
-$(AUTOLOADS): $(ELFILES) haskell-mode.elc
+$(AUTOLOADS): $(ELFILES)
 	$(BATCH) \
 		--eval '(setq make-backup-files nil)' \
 		--eval '(setq generated-autoload-file "$(CURDIR)/$@")' \
 		-f batch-update-autoloads "."
+	# check if autoloads will really load
+	$(BATCH) -l "$@"
